version: '3.4'

services:
  redis:
    image: redislabs/redismod:preview
    volumes:
      - ../redis-server/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - default
  
  
  rabbitmq:
    image: rabbitmq
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    expose:
      - 5672
      - 15672
    networks:
      - default
